### ISSUE TITLE
WarpGate Requirement

### ISSUE THREAD

**Issue by dogstarrb** [MrVauxs/pf2e-jb2a-macros#190]
As WarpGate is now so defunct as to not be installable, is it possible we can remove that dependency? It has been taken down from github, it seems.

**Comment by fishrobe** [comment]
> As WarpGate is now so defunct as to not be installable, is it possible we can remove that dependency? It has been taken down from github, it seems.

The creator of Warpgate threw a tantrum about "bootlegs" of their GPL v3 Open Liscence software being made because people were forking a module they weren't even updating anymore and took it down, screwing everyone who had a dependency on it.  It seems like some animations work and some don't now. Looking for a workaround myself.
