### ISSUE TITLE
The pf2e-jb2a-macros.Macros Datastore is not yet connected!

### ISSUE THREAD

**Issue by samerogers** [MrVauxs/pf2e-jb2a-macros#98]
I have installed the prereqs, including Automated Animations, Advanced Macros, and the Patreon version of JB2A. Unfortunately adding and removing certain effects from characters causes this message to pop up. I am currently using Foundry 10.291.

**Comment by samerogers** [comment]
It appears that the Macros compendium is still having issues loading for the new Sequencer version.

**Comment by jdwpom** [comment]
Just went through and manually deleted my entire autorec menu, then re-imported from 2.9.6, and this issue appears to have gone. My assumption is that it wasn't updating some of the ones that were already there, and starting from scratch gets you the latest versions of the macros from this module.

In saying that, I also rebooted the computer on which Foundry is running, so that might be it, too. Sorry. I was running game in 5 minutes and needed to fix it, not test it.

**Comment by samerogers** [comment]
Issue resolved after rebooting my docker instance. Looks like the older version's files were cached until full reboot.

**Comment by MrVauxs** [comment]
Yeah, it was the 2.9.5 version being absolutely bricked.
